# configuration based on:
# - https://github.com/syssi/esphome-yeelight-ceiling-light/blob/main/yeelight_light_ceiling15.yaml

substitutions:
  name: yeelight-light-ceiling24

esphome:
  name: ${name}
  min_version: 2024.10.0

esp32:
  board: esp32doit-devkit-v1
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_FREERTOS_UNICORE: y
    advanced:
      ignore_efuse_mac_crc: true
      ignore_efuse_custom_mac: true

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

ota:
  platform: esphome

logger:
  level: DEBUG
  baud_rate: 0

api:

sensor:
  - platform: adc
    pin: GPIO32
    name: "${name} adc1"
    attenuation: 12db
  - platform: adc
    pin: GPIO33
    name: "${name} adc2"
    attenuation: 12db

output:
  - platform: ledc
    pin: GPIO19
    id: output_warm
  - platform: ledc
    pin: GPIO21
    id: output_cold

light:
  - platform: cwww
    name: "${name} ceiling light"
    id: ceiling_light
    cold_white: output_cold
    warm_white: output_warm
    cold_white_color_temperature: 6500 K
    warm_white_color_temperature: 2700 K
    # disabling constant_brightness makes color temperature transition smooth without brightness dips
    # constant_brightness: true
    gamma_correct: 0
