# merged configuration of:
# - https://github.com/syssi/esphome-yeelight-ceiling-light/blob/main/yeelight_light_ceiling15.yaml
# - https://github.com/jaddel/ESPHome-Configurations/blob/master/Devices/Ceiling%20Yeelight%20YLXD41YL/ceiling_yeelight_ylxd41xl.yaml

substitutions:
  name: yeelight-light-ceiling11

esphome:
  name: ${name}
  min_version: 2024.10.0

esp32:
  board: esp32doit-devkit-v1
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_FREERTOS_UNICORE: y
      # Please uncomment these parameters if fast booting is important to you
      # CONFIG_BOOTLOADER_SKIP_VALIDATE_ON_POWER_ON: y
      # CONFIG_BOOTLOADER_LOG_LEVEL_NONE: y
      # CONFIG_LOG_DEFAULT_LEVEL_NONE: y
    advanced:
      ignore_efuse_mac_crc: true
      ignore_efuse_custom_mac: true

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

ota:
  platform: esphome

logger:
  level: DEBUG
  baud_rate: 0

api:

sensor:
  - platform: adc
    pin: GPIO36
    name: "${name} adc1"
    attenuation: 12db
  - platform: adc
    pin: GPIO32
    name: "${name} adc2"
    attenuation: 12db

output:
  - platform: ledc
    pin: GPIO19
    id: output_warm
    frequency: 4882Hz
  - platform: ledc
    pin: GPIO21
    id: output_cold
    frequency: 4882Hz
  - platform: ledc
    pin: GPIO23
    id: output_nightlight
    frequency: 19531Hz

light:
  - platform: monochromatic
    name: "${name}-nightlight"
    id: night_light
    output: output_nightlight
    gamma_correct: 0.7
    on_turn_on:
      - light.turn_off: ceiling_light
  - platform: cwww
    name: "${name}"
    id: ceiling_light
    cold_white: output_cold
    warm_white: output_warm
    cold_white_color_temperature: 6500 K
    warm_white_color_temperature: 2700 K
    constant_brightness: true
    gamma_correct: 0.4
    on_turn_on:
      - light.turn_off: night_light
