substitutions:
  name: yeerc
  external_components_source: github://syssi/esphome-yeelight-ceiling-light@main

esphome:
  name: ${name}

esp32:
  board: esp32doit-devkit-v1
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_FREERTOS_UNICORE: y
    advanced:
      ignore_efuse_mac_crc: true
    # Bugfix for ESPHome 2022.12.0 and up: fallback to older platform
    # version, to prevent bricked devices. ESPHome uses newer versions
    # by default.
    # See also: https://github.com/mmakaay/esphome-xiaomi_bslamp2/issues/104
    version: 4.3.2
    source: ~3.40302.0
    platform_version: platformio/espressif32 @ 3.5.0

external_components:
  - source: ${external_components_source}
    refresh: 0s

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true

ota:

logger:
  level: DEBUG

api:

esp32_ble_tracker:
  scan_parameters:
    interval: 150ms
    window: 150ms
    duration: 1min
    active: false

xiaomi_ylyk01yl:
  mac_address: "A4:C1:38:6C:23:2D"
  last_button_pressed:
    name: "last button pressed"

  # Button  Keycode (YLYK01YL Ceiling Lamp)
  # on      0
  # off     1
  # sun     2
  # +       3
  # m       4
  # -       5
  on_press:
    - keycode: 0
      then:
        - logger.log: "Button on pressed"
    - keycode: 1
      then:
        - logger.log: "Button off pressed"
    - keycode: 2
      then:
        - logger.log: "Button sun pressed"
    - keycode: 3
      then:
        - logger.log: "Button + pressed"
    - keycode: 4
      then:
        - logger.log: "Button m pressed"
    - keycode: 5
      then:
        - logger.log: "Button - pressed"

    # Trigger on any keycode
    - then:
        - logger.log:
            format: 'Button with keycode %d pressed'
            args: ['int(keycode)']

  on_long_press:
    - keycode: 0
      then:
        - logger.log: "Button on long pressed"
    - keycode: 1
      then:
        - logger.log: "Button off long pressed"
    - keycode: 2
      then:
        - logger.log: "Button sun long pressed"
    - keycode: 3
      then:
        - logger.log: "Button + long pressed"
    - keycode: 4
      then:
        - logger.log: "Button m long pressed"
    - keycode: 5
      then:
        - logger.log: "Button - long pressed"

    # Trigger on any keycode
    - then:
        - logger.log:
            format: 'Button with keycode %d long pressed'
            args: ['int(keycode)']
